// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evlkagwvhducaukxhcdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bGthZ3d2aGR1Y2F1a3hoY2RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMjk1NjYsImV4cCI6MjA1NTkwNTU2Nn0.A6pJIPEbuBGThpz9wrXbXwmoUrN4fmTp0FWA0i8KHL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);